# Generated by Django 4.1.7 on 2023-02-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0002_rename_details_run_category_rename_subject_run_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='dur',
            field=models.IntegerField(default=0),
        ),
    ]
