# Generated by Django 4.1.7 on 2023-02-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0003_run_dur'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
