# Generated by Django 4.1.7 on 2023-02-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run', '0004_run_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distance',
            field=models.IntegerField(default=None, blank = True, null=True),
        ),
    ]
